import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "../utils/api";

const Home: NextPage = (props) => {


  return (
    <>
      <Head>
        <title>Note Taking App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid h-screen place-items-center">
          <div className="flex flex-col items-center">
            <div className="text-2xl">Please sign in to start taking notes</div>
            <button onClick={() => void signIn('github', { callbackUrl: `/topics` })}>Sign in</button>
            <p>{}</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
